# ===================================
# Filter Scope Definitions
# ===================================

scopes:
    id_group:
        label: ID Group
        type: group
        conditions: id in (:filtered)
        options:
            '1': One
            '2': Two
            '3': Three
    id_range:
        label: ID Range
        type: numberrange
        conditions: id >= ':min' and id <= ':max'
