# ===================================
#  Relation Behavior Config
# ===================================

person:
    label: Person
    list: $/october/test/models/person/columns.yaml
    form: $/october/test/models/person/fields.yaml
