# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Post

# Model Form Field configuration
form: $/october/test/models/post/fields.yaml

# Model Class name
modelClass: October\Test\Models\Post

# Default redirect location
defaultRedirect: october/test/posts

# Create page
create:
    title: Create Posts (Custom Text)
    redirect: october/test/posts/update/:id
    redirectClose: october/test/posts

# Update page
update:
    title: Edit Posts (Awesome Title)
    redirect: october/test/posts
    redirectClose: october/test/posts

# Preview page
preview:
    title: Preview Posts
