# ===================================
#  Import/Export Behavior Config
# ===================================

export:
    useList: posts
    fileName: posts.csv

defaultFormatOptions:
    fileFormat: json
