# ===================================
# Filter Scope Definitions
# ===================================

scopes:

    post:
        label: Post
        modelClass: October\Test\Models\Post
        conditions: post_id in (:filtered)
        nameFrom: name

    content:
        label: Content
        type: text
        conditions: content = :value
