# ===================================
#  Relation Behavior Config
# ===================================

phone:
    label: Phone
    form: $/october/test/models/phone/fields_simple.yaml
    list: $/october/test/models/phone/columns.yaml
