# ===================================
#  Used as a Repeater Model
# ===================================

editor:
    name: Text Editor
    icon: icon-file-text-o
    fields:
        content:
            type: richeditor
            size: large

gallery:
    name: Photos
    icon: icon-file-image-o
    fields:
        photos:
            type: fileupload
            mode: image
            imageWidth: 200
            imageHeight: 200

sister:
    name: Sister
    icon: icon-refresh
    fields:
        sisters:
            label: Sister
            prompt: Add sister
            span: full
            type: repeater
            form: $/october/test/config/repeater_country_sisters.yaml
