# ===================================
#  Used as a Repeater Model
# ===================================

fields:
    title:
        label: State
    subtitle:
        label: Suburb
        span: full
    photos:
        label: Photos
        type: fileupload
        mode: image
        imageWidth: 200
        imageHeight: 200
