# ===================================
#  Used as a Repeater Model
# ===================================

fields:
    title:
        label: State
        span: auto
    subtitle:
        label: Suburb
        span: auto
    is_enabled:
        label: Enabled
        type: switch
        span: auto
    is_default:
        label: Default
        type: switch
        span: auto
    photos:
        label: Photos
        type: fileupload
        mode: image
        imageWidth: 200
        imageHeight: 200
