# ===================================
#  Relation Behavior Config
# ===================================

country:
    label: Country
    form: $/october/test/models/country/fields_simple.yaml
    list: $/october/test/models/country/columns_simple.yaml

locations:
    label: Location
    list: ~/plugins/october/test/models/location/columns.yaml
    form: ~/plugins/october/test/models/location/fields.yaml
    manage:
        recordsPerPage: 10
        showSearch: true
    structure:
        showTree: true
        showReorder: true
