
posts:
    label: Posts
    list: ~/plugins/october/test/models/post/columns.yaml
    form: ~/plugins/october/test/models/post/fields_simple.yaml
#    manage:
#        context: relation

countries:
    label: Country
    list: ~/plugins/october/test/models/country/columns_simple.yaml
    form: ~/plugins/october/test/models/country/fields_simple.yaml
    structure:
        showReorder: true
        showTree: false
