
posts:
    label: Posts
    list: $/october/test/models/post/columns.yaml
    form: $/october/test/models/post/fields_simple.yaml
    view:
        filter: $/october/test/models/post/scopes.yaml
    manage:
        showSearch: true
        filter: $/october/test/models/post/scopes.yaml

countries:
    label: Country
    list: $/october/test/models/country/columns_simple.yaml
    form: $/october/test/models/country/fields_simple.yaml
    structure:
        showReorder: true
        showTree: false
